apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-server
  template:
    metadata:
      labels:
        app: ws-server
    spec:
      containers:
        - name: ws-server
          image: ws-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8765
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
